### ISSUE TITLE
Hide scroll on bottom

### ISSUE THREAD

**Issue by irfan-yusanif** [solodev/featured-content-slider#1]
Hi,
the slider shows a scroll bar on bottom, how can we hide that scroll bar from bottom without effecting the style, and when page width is below 667px the slider image is not completely shown. How can we make it responsive.

**Comment by smmadara** [comment]
For the scroll bar, you would just need to add "overflow: hidden;" to the CSS for the primary HTML or Body tag. To ensure the full image shows on smaller devices, you can remove the "object-fit: cover;" property from the .slide-item >> .slide-photo >> img class.
